services:

  _instanceof:
    Sauls\Bundle\ObjectRegistryBundle\Manager\ManagerInterface:
      shared: false
      tags: ['sauls.object_manager']

  Sauls\Bundle\ObjectRegistryBundle\Collection\ObjectManagerCollection:
    arguments:
      - [!tagged sauls.object_manager]
  Sauls\Bundle\ObjectRegistryBundle\Collection\ObjectManagerCollectionInterface: '@Sauls\Bundle\ObjectRegistryBundle\Collection\ObjectManagerCollection'

  Sauls\Bundle\ObjectRegistryBundle\Registry\ObjectRegistry: ~
  Sauls\Bundle\ObjectRegistryBundle\Registry\ObjectRegistryInterface: '@Sauls\Bundle\ObjectRegistryBundle\Registry\ObjectRegistry'

  Sauls\Bundle\ObjectRegistryBundle\Manager\Batch\PersistentBatchObjectsManager:
    shared: false

  Sauls\Bundle\ObjectRegistryBundle\Manager\Batch\PersistentBatchObjectsManagerInterface: '@Sauls\Bundle\ObjectRegistryBundle\Manager\Batch\PersistentBatchObjectsManager'
